// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
// ...
/*await Firebase.initializeApp(
  options: DefaultFirebaseOptions.currentPlatform,
);*/
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvUDOE1JKk9unN4cThbTmjR5GOPBm7wFY',
    appId: '1:788312756741:web:1bdd4f768dbe356af0826c',
    messagingSenderId: '788312756741',
    projectId: 'localfoodie-fbd5b',
    authDomain: 'localfoodie-fbd5b.firebaseapp.com',
    storageBucket: 'localfoodie-fbd5b.appspot.com',
    measurementId: 'G-YSVRTG9P7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbh5BFKuOIoALLOCv3y1vBkeu9zgtN57o',
    appId: '1:788312756741:android:fb273f53e118f00ff0826c',
    messagingSenderId: '788312756741',
    projectId: 'localfoodie-fbd5b',
    storageBucket: 'localfoodie-fbd5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAymTJrREBYa73qCjEw0vMmWxKy9f1Ayx0',
    appId: '1:788312756741:ios:ca623b8829b5dd50f0826c',
    messagingSenderId: '788312756741',
    projectId: 'localfoodie-fbd5b',
    storageBucket: 'localfoodie-fbd5b.appspot.com',
    iosClientId:
        '788312756741-8pd1a62k8ik7uj5jusebs6ue03888dsg.apps.googleusercontent.com',
    iosBundleId: 'com.example.localFoodie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAymTJrREBYa73qCjEw0vMmWxKy9f1Ayx0',
    appId: '1:788312756741:ios:4fab2597b994dd2af0826c',
    messagingSenderId: '788312756741',
    projectId: 'localfoodie-fbd5b',
    storageBucket: 'localfoodie-fbd5b.appspot.com',
    iosClientId:
        '788312756741-ecg36ifpbd2tr9maco57lnv2je96t8u9.apps.googleusercontent.com',
    iosBundleId: 'com.example.localFoodie.RunnerTests',
  );
}

//AI


